---
apiVersion: v1
kind: Service
metadata:
  name: cc-final-redis-service
  labels:
    username: cc
    env: final
spec:
  type: ClusterIP
  selector:
    app: cc-final-redis
  ports:
  - name: cc-final-redis-service
    port: 6379
    targetPort: 6379
