---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conor-hw7-worker
  labels:
    username: conor
    app: conor-hw7-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: conor-hw7-worker
  template:
    metadata:
      labels:
        username: conor
        app: conor-hw7-worker
    spec:
      containers:
        - name: conor-hw7-worker
          imagePullPolicy: Always
          image: conordonihoo/hw7:1.8
          command: ["python", "worker.py"]
          env:
          - name: WORKER_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: REDIS_IP
            value: 10.105.233.147
