---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: conor-hw7-data
  labels:
    username: conor
    env: hw7
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 1Gi

