---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cc-final-worker-transaction
  labels:
    username: cc
    app: cc-final-worker-transaction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cc-final-worker-transaction
  template:
    metadata:
      labels:
        username: cc
        app: cc-final-worker-transaction
    spec:
      containers:
        - name: cc-final-worker-transaction
          imagePullPolicy: Always
          image: conordonihoo/coe332final:latest
          volumeMounts:
          - name: cc-final-data
            mountPath: "/tmp"
          command: ["python", "worker_transaction.py"]
          env:
          - name: WORKER_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: REDIS_IP
            value: 10.102.92.99
      volumes:
      - name: cc-final-data
        persistentVolumeClaim:
          claimName: cc-final-data
