---
apiVersion: v1
kind: Service
metadata:
  name: cc-final-flask-service
  labels:
    username: cc
    env: final
spec:
  type: ClusterIP
  selector:
    app: cc-final-flask
  ports:
  - name: cc-final-flask-service
    port: 5000
    targetPort: 5000
